version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  
  # Com a configuração abaixo a aplicação apresenta erro de conexão, foi necessário a alteração.
  # db:
  #   image: bitnami/mongodb:5.0.17
  #   volumes:
  #     - mongodb_data:/bitnami/mongodb
  #   environment:
  #     MONGODB_ROOT_PASSWORD: root
  #     MONGODB_REPLICA_SET_MODE: primary
  #     MONGODB_REPLICA_SET_KEY: 123456
  #     MONGODB_DATABASE: nest
  
    
  db:
    build: ./mongo_replica
    restart: always
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: db
      MONGODB_DATABASE: nest
       
volumes:
  mongodb_data:
    driver: local

networks:
  my-network:
    external: true